// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQdV0eH0WuPE_-mlRncWjIj2MJ5d4Yc4o',
    appId: '1:733450174508:web:fa51521396ca4c01109189',
    messagingSenderId: '733450174508',
    projectId: 'authentification-flutter-b4327',
    authDomain: 'authentification-flutter-b4327.firebaseapp.com',
    storageBucket: 'authentification-flutter-b4327.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4LEsHh4qWD3Wf9HR8qGOc0dMyEJLYc0',
    appId: '1:733450174508:android:27a9907ba4905651109189',
    messagingSenderId: '733450174508',
    projectId: 'authentification-flutter-b4327',
    storageBucket: 'authentification-flutter-b4327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44AoJ5P-HAJjXm2CZE19hGpIXTAmcI6s',
    appId: '1:733450174508:ios:1e3d0b22c9ebde5c109189',
    messagingSenderId: '733450174508',
    projectId: 'authentification-flutter-b4327',
    storageBucket: 'authentification-flutter-b4327.appspot.com',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44AoJ5P-HAJjXm2CZE19hGpIXTAmcI6s',
    appId: '1:733450174508:ios:065e59969bd2cf58109189',
    messagingSenderId: '733450174508',
    projectId: 'authentification-flutter-b4327',
    storageBucket: 'authentification-flutter-b4327.appspot.com',
    iosBundleId: 'com.example.authentification.RunnerTests',
  );
}
